wrapper/hosts.py, wrapper/tests/test_v2v_args.py, wrapper/virt_v2v_wrapper.py
When moving to a container only approach, we mount conversion host folders in the container at runtime to store state and limits, as well as logs outside of the container. In the existing implementation, the folders for logs are different depending on the destination provider:
- `/var/log/vdsm/import` for RHV
- `/var/log/virt-v2v` for OpenStack
- `/tmp` for CNV
This pull request standardize them the `/var/log/uci`. From a conversion host point of view, ManageIQ creates `/var/log/uci/<task_id>` folder and mounts it to `/var/log/uci` in the container to isolate each migration task: https://github.com/ManageIQ/manageiq/pull/19698.
With this change, there no need to apply a tag to the file names to differentiate them. This pull request removes the tag from the file names and makes them …
=> Standardize runtime and log folders for UCI

wrapper/checks.py, wrapper/hosts.py, wrapper/tests/test_rhv.py, wrapper/virt_v2v_wrapper.py
When moving to a container only approach, we ship the virtio-win package within the container, which means that we don't need to scrape the storage domains to find the ISO image.
This pull request removes the code related to checking the drivers image.
=> Remove ISO domain inspection

.travis.yml, tox.ini, v2v-conversion-host.spec.in, wrapper/hosts.py, wrapper/log_parser.py, wrapper/runners.py, wrapper/tests/test_routines.py, wrapper/virt_v2v_wrapper.py
When moving to a container only approach, the container image is built from `rhel8` or `centos8` image. In these images, Python 3 is the default version. And Python 2 is officially deprecated in the language itself. This pull request removes code and tests specific to Python 2.
Note: `wrapper/tc.py` file is left untouched as it will be altered in another pull request.
=> Remove Python 2 specific code and tests

docs/Virt-v2v-wrapper.md, wrapper/checks.py, wrapper/hosts.py, wrapper/tests/test_ovirt.py, wrapper/tests/test_v2v_args.py, wrapper/tests/testrunner.py, wrapper/virt_v2v_wrapper.py
When moving to a container only approach, `virt-v2v-wrapper` will not have access to the oVirt host resources and will run as `root`. This means that we can cleanup the code. This pull request does the following things:
- Rename RHV to oVirt wherever possible (`virt-v2v` uses `rhv` in its options names)
- Remove code related to export domain as we only use `rhv_upload` mechanism
- Enforce `direct` backend for all providers
- Remove `VDSM` related constants and variables in `OvirtHost` class
- Remove CA certificate path for `ovirtsdk4` code
Note: we still need CA certificate path for `virt-v2v`, because it's a mandatory option [[BZ#1791240](https://bugzilla.redhat.com/show_bug.cgi?id=1791240)]. The path is fixed, so we make it a constant.
=> Remove code related to RHV host

wrapper/hosts.py, wrapper/log_parser.py, wrapper/tests/test_openstack.py, wrapper/tests/test_output_parser.py, wrapper/tests/testrunner.py, wrapper/virt_v2v_wrapper.py
In the current implementation, the code uses the downstream projects names for the various classes and variables names. The manageiq-v2v-conversion_host project is an upstream project, so we should prefer upstream projects names whenever possible.
This pull request replaces `RHV` with `oVirt`, `OSP` with `Openstack` and `CNV` with `Kubevirt` whenever possible. Some occurences are still present:
- Some attributes of the input `data` are still prefixed with `rhv` or `osp`. They can be renamed jointly with the ServiceTemplateTransformationPlanTask that generates it. It will be done in separate pull requests.
- Some options of `virt-v2v` use `rhv` or `osp`. This would require changes in `libguestfs` and `virt-v2v`, so it will take more time, if it's ever implemented.
Built on …
=> Rename downstream to upstream

kubevirt-conversion/entrypoint
In existing implementation, virt-v2v-wrapper reads the configuration from its standard input. For migration to Kubevirt, it was decided to store it in `/data/input/conversion.json` file. With ManageIQ, we thought that it might be interesting to have all persistent assets in `/var/lib/uci`.
In order to not break Kubevirt code, this pull request links `/data/input/conversion.json` as `var/lib/uci/input.json`. It also update the path of the input file to use `/var/lib/uci/input.json`.
=> Use input from /var/lib/uci in entrypoint

wrapper/checks.py, wrapper/hosts.py, wrapper/virt_v2v_wrapper.py
We quickly discussed the opportunity to standardize string formatting mechanism in wrapper. It seems that f-strings don't play well with `logging`, so we can't really standardize on f-strings. The `.format` method seems a bit old school and the `%` notation is pretty explicit. This pull request proposes standardizing with `%` notation. And this requires just a few changes.
=> Standardize string formatting with % notation

wrapper/common.py, wrapper/state.py, wrapper/virt_v2v_wrapper.py
The `write_password` method could be used outside of `virt-v2v-wrapper.py`, for example to create the oVirt password file during `validate_data` method in `host.py`. This pull request moves it to `common.py` and updates existing calls. It also stores the password files paths to `STATE.internal['password_files']` to have central place accessible from all classes.
=> Move write_password method to common

.travis.yml
The output is nicer in files where the carriage returns (`\r`s) don't do what they do in the terminal.
=> travis: Disable tox spinner for parallel builds

wrapper/hosts.py, wrapper/pre_copy.py, wrapper/virt_v2v_wrapper.py
There are few different changes in this:
* we are not throwing away the logs from nbdkits
* we are requesting list of allocated extents of disks using pyvmomi
* block stats are not requested for the whole disk, but rather only for those
extents that have data
* there's a new function `copy_ref` that helps us refer to the right copy
instance from the list of copies based on whether this is the final copy
(which was the only one in two-phase conversion) or an "intermediate" or
"warm" copy
* there are some fixes implemented, for example closing the file and the nbd
handle upon failure, removal of some unused class members, cleaning up of
nbdkit sockets and simplification of vmware_password_file being passed around
=> Warm conversion

wrapper/log_parser.py, wrapper/tests/test_output_parser.py
The log format of virt-v2v has changed and it now contains the transport method, as well the disk number. This breaks the progress reporting in state file. This pull request updates the regular expression.
RHBZ: https://bugzilla.redhat.com/show_bug.cgi?id=1810040
=> Update regexp for nbdkit disk path

.travis.yml
=> automation: make python 3.9-dev builds optional

.travis.yml
Travis seems to fail on it from time to time for unknown reason.
=> automation: run `./build.sh prep` verbosely

wrapper/common.py, wrapper/virt_v2v_wrapper.py
Recently, we've seen some failures in migration check, such as VM already existing in destination. While it's normal to perform checks before transferring disks, the problem is that the state file doesn't exist at that moment and this prevents reporting errors outside of logs.
This pull request make virt-v2v-wrapper create the state file earlier, i.e. right after getting the host.
RHBZ: https://bugzilla.redhat.com/show_bug.cgi?id=1809033
=> Write the state file early

wrapper/hosts.py
It appears that the disk creation cant take more than the allowed 5 minutes under heavy load. 
Doubling to 10 minutes should cover most cases.
RHBZ: https://bugzilla.redhat.com/show_bug.cgi?id=1817341
=> Increase disks operations timeout

kubevirt-vmware/pkg/controller/ovirtprovider/client.go
This PR fixes an issue with empty disk name. We should use alias from `disk` object not `diskattachement` name to provide this information.
There is similar situation with disk id. We should get this value from `disk` object not `diskattachement`.
=> Fetch disk id and name using disk object 

wrapper/hosts.py
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1820671
=> OpenstackHost: Do not list attached paths for single-phase conversion

requirements.txt, setup.py, wrapper/common.py, wrapper/hosts.py, wrapper/log_parser.py, wrapper/pre_copy.py, wrapper/tests/test_pre_copy.py, wrapper/virt_v2v_wrapper.py
This series introduces three main things:
1) When creating a snapshot fails, try again.
1) Do not parse overlay file names from the log output.
1) When copy iteration fails, retry during the next iteration (this Fixes #27 ).
Missing things so that this is not a draft any more:
And maybe also (unless we decide otherwise):
=> Various fixes for warm migration

wrapper/pre_copy.py
... or in location of LIBGUESTFS_CACHEDIR if that one is set.
=> pre_copy: make sure overlay files are in /var/tmp

kubevirt-vmware/pkg/controller/ovirtprovider/client.go
In order to properly map source and target networks we need network id and name. This PR provides both.
=> kubevirt: add network id and name

docs/Virt-v2v-wrapper.md, requirements.txt, setup.py, wrapper/exports.py, wrapper/hosts.py, wrapper/source_hosts.py, wrapper/virt_v2v_wrapper.py
Here is an attempt at direct migrations from one OpenStack cloud to another.
It works using two conversion hosts, one in an instance on the source OpenStack cloud and one in an instance on the destination OpenStack cloud. Volumes are detached from their source instances and attached to the source conversion host, and exported from inside the source conversion host with nbdkit. The destination conversion host performs all the OpenStack API manipulations and converts the exports to new destination volumes attached to itself.
After the transfer is complete, the wrapper's existing OpenStack host support starts a new instance with the newly created volumes.
=> OpenStack-to-OpenStack migration review

.yamllint
I tried this in the past but it did not work properly for some reason.
But it seems to work now so let's use that as it is easier than listing
all the (broken) files from vednored dependencies.
=> automation: exclude Go deps from yamllint check

wrapper/tests/test_output_parser.py
New version of flake8 does not like trivial names. This fixes the error:
E741 ambiguous variable name 'l'
=> tests: fix ambiguous variable name

.gitignore, build.sh, kubevirt-vmware/cmd/manager/main.go, kubevirt-vmware/go.mod, kubevirt-vmware/pkg/apis/addtoscheme_v2v_v1alpha1.go, kubevirt-vmware/pkg/controller/add_v2vvmware.go, kubevirt-vmware/pkg/controller/garbage_collector/v2vvmware_garbagecollector.go, kubevirt-vmware/pkg/controller/gcovirtprovider/ovirtprovider_garbagecollector.go, kubevirt-vmware/pkg/controller/ovirtprovider/client.go, kubevirt-vmware/pkg/controller/ovirtprovider/ovirtprovider_controller.go, kubevirt-vmware/pkg/controller/v2vvmware/actions.go, kubevirt-vmware/pkg/controller/v2vvmware/v2vvmware_controller.go, kubevirt-vmware/pkg/controller/v2vvmware/vmware.go, wrapper/tests/test_output_parser.py
Changed the kubevirt-vmware package name to reflect current location of the repository.
`wrapper/tests/test_output_parser.py` changes are part of #60; included here to satisfy Travis build.
Signed-off-by: Jakub Dzon <jdzon@redhat.com>
=> ovirt: change kubevirt-vmware package

kubevirt-vmware/pkg/controller/ovirtprovider/client.go
We would like to warn user about running vm before stopping it.
Fixes: https://github.com/ManageIQ/manageiq-v2v-conversion_host/issues/65
=> ovirt: expose vm status information

wrapper/virt_v2v_wrapper.py
It was reported that one of the log messages doesn't look "professional". This pull request removes the "Hack, hack..." part in the message about the "direct" backend.
RHBZ: https://bugzilla.redhat.com/show_bug.cgi?id=1821209
=> Fix unprofessional log message

ansible/oVirt.v2v-conversion-host/tasks/install-provider-rhevm.yml, ansible/oVirt.v2v-conversion-host/tasks/install-virt-v2v.yml, ansible/oVirt.v2v-conversion-host/tasks/main.yml
Some packages are named differently on EL8 so we have to update the
requirements accordingly.
=> ansible: update the deployment to work on EL8

wrapper/common.py, wrapper/virt_v2v_wrapper.py
Backport of https://github.com/ManageIQ/manageiq-v2v-conversion_host/pull/30 to v1.x branch.
RHBZ: https://bugzilla.redhat.com/show_bug.cgi?id=1809033
=> Write the state file early (v1.x)

build.sh
Do not include the Kubevirt content as it makes the package
unnecessarily large. The releases from master branch are the proper
source of the source files if anyone wishes to use the dist package (and
not to use git repo). As for the kubevirt v2v container the source is in
MangeIQ/manageiq-v2v-conversion_host-build repository.
=> build: remove Kubevirt content from dist package

ansible/oVirt.v2v-conversion-host/tasks/install-validate-rhevm.yml, wrapper/checks.py
This is broken on EL8 host because the yum python module is not
installed by default. But oVirt 4.2 is long obsolete and we don't
really support anything but the latest version anyway.
=> remove check for oVirt version

wrapper/hosts.py, wrapper/tests/test_rhv.py
`os.walk()` returns names as `str` which means `os.listdir()` will also
return names as `str`. That all means our patterns have to be `str` too.
=> wrapper: tools patterns have to be str not bytes

kubevirt-vmware/pkg/controller/ovirtprovider/client.go
We need to make sure we can handle urls when procotol is not provided. In this case we default to https.
Bug-Url: https://bugzilla.redhat.com/1849733
=> Handle urls when protocol is not provided

kubevirt-vmware/pkg/controller/ovirtprovider/client.go
When we try to import a vm without vnicProfiles it causes provider pod to crash. This PR fixes the issue.
Bug-Url: https://bugzilla.redhat.com/1851886
=> Handle missing vnicProfiles

kubevirt-vmware/pkg/controller/ovirtprovider/client.go
In order to filter networks by type on the UI we need to provide whether specific network uses sriov.
=> Provide whether network is sriov

kubevirt-vmware/pkg/controller/ovirtprovider/ovirtprovider_controller.go
When we fail to verify credentials we used to requeue verification without any timeout. This cycle was done for 5mins. With this PR
we reduce timeout to 1min with 10secs requeue delay.
=> Reduce number of connect retries

wrapper/hosts.py
Some lines got miss-aligned during refactoring (commit 9c0c59c). This
breaks POD annotation updateds in Kubevirt.
=> wrapper: fix indentation in CNVHost

wrapper/virt_v2v_wrapper.py
We did not update the progress after virt-v2v finished. This could
result in situations where the progress remained on number that was less
than 100% in Kubevirt. Let's call update on progress one last time to
make sure it reaches 100%.
=> wrapper: final progress update after virt-v2v finished (RHBZ# 1878460)

go.mod
Red Hat is building an image of this repository in it's internal build system that requires a go.mod
file in the root so that it can get the dependencies, this PR creates symlink file in the root that references the go.mod file.
Signed-off-by: Nikolas Komonen <nkomonen@redhat.com>
=> Added symlink to go.mod file in root

ansible/oVirt.v2v-conversion-host/tasks/install-transport-vddk.yml
When running the playbook against oVirt 4.4, the `nbdkit-plugin-vddk` package doesn't exist. It has been renamed to `nbdkit-vddk-plugin` on EL8. This pull request adds conditions to support both EL7 and EL8.
=> Install nbdkit-vddk-plugin on EL 8

ansible/oVirt.v2v-conversion-host/tasks/install-transport-vddk.yml
In Advanced Virtualization on EL8 we don't have to explicitly
check/install VDDK plugin for nbdkit. virt-v2v in Advanced
Virtualization explicitly requires nbdkit which explicitly requires the
VDDK plugin.
Note: This is true only for package from Advanced Virtualization, but we
don't expect anyone using the packages from base EL!
=> ansible: don't explicitly check for VDDK plugin

wrapper/hosts.py
When we use systemd-run on RHV conversion host the environment variables USER and HOME are not configured for the vdsm user. They have to be dropped from environment in order for systemd-run to supply the correct values.
=> wrapper: drop USER and HOME from env when using SystemdRunner (RHBZ#1901423)

ansible/oVirt.v2v-conversion-host/tasks/uninstall-provider-openstack.yml
If the installation role was incomplete and didn't create the /etc/cron.daily/virt-v2v-logs file, then the role would fail when trying to uninstall it as the `state` is not specified.
=> Fix /etc/cron.daily/virt-v2v-logs removal

ansible/oVirt.v2v-conversion-host/tasks/install-provider-openstack.yml, wrapper/hosts.py
While our current assumption is that the conversion host is based on EL7 for OpenStack, it may happen that a user wants to use EL8 to benefit from more recent versions of virt-v2v and nbdkit, e.g. to use VDDK 7.0. This pull request adds support for the new names of the packages in EL 8. It has been tested in a real environment.
=> Allow OpenStack conversion host based on EL8
