- .gitignore
- .travis.yml
- Pipfile
- docs/Virt-v2v-wrapper.md
- requirements.txt
- setup.py
- tox.ini
- v2v-conversion-host.spec.in
- wrapper/common.py
- wrapper/hosts.py
- wrapper/log_parser.py
- wrapper/pre_copy.py
- wrapper/runners.py
- wrapper/state.py
- wrapper/tests/mocks/nbd.py
- wrapper/tests/test_output_parser.py
- wrapper/tests/test_ovirt.py
- wrapper/tests/test_pre_copy.py
- wrapper/tests/test_state.py
- wrapper/tests/test_v2v_args.py
- wrapper/tests/testrunner.py
- wrapper/virt_v2v_wrapper.py
This PR implements two-phase conversion.
> Implement two-phase conversion and add support for it in OvirtHost

- wrapper/pre_copy.py
When there is no output `readline()` returns an empty string instead of
`errno.EAGAIN`, although I'm keeping that still handled just in case.
> pre_copy: Do not spin unnecessarily when there is no output

- wrapper/pre_copy.py
This way old-style conversion still works without libnbd installed.
> pre_copy: Do not require nbd unless it is really needed

- .travis.yml
- build.sh
- wrapper/meta.py
There were still few issues created by tinkering with meta.py.
> Fix the mess around meta.py

- ansible/manageiq.v2v-conversion-host/tasks/check-transport-vddk-facts.yml
- ansible/manageiq.v2v-conversion-host/tasks/check-transport-vddk.yml
- ansible/manageiq.v2v-conversion-host/tasks/install-transport-ssh.yml
- ansible/manageiq.v2v-conversion-host/tasks/install-transport-vddk.yml
- ansible/manageiq.v2v-conversion-host/tasks/uninstall-transport-ssh.yml
- docs/Ansible.md
While testing the configuration of a conversion host based on UCI, we identified a few issues. This pull request fixes these issues and updates the documentation.
> Continue refactoring role for UCI

- wrapper/pre_copy.py
During testing it happened to me that one disk was fully allocated and the copy was over a very slow connection.  And because it took over 3 hours to finish the timeout on the pyvmomi connection resulted in a unauthorized connection for the very next API. This safely fixes it and ofr a good measure in two places at the same time. Since we're not multi-threaded it should not be an issue.
> Keep VMWare connection alive even during long copy blocks

- wrapper/hosts.py
- wrapper/pre_copy.py
- wrapper/pyvmomi_wrapper.py
> pre_copy: Do not require pyvmomi unless it is really needed 

- docs/Virt-v2v-wrapper.md
- requirements.txt
- setup.py
- wrapper/hosts.py
- wrapper/osp_wrapper.py
- wrapper/pre_copy.py
- wrapper/tests/test_osp_wrapper.py
- wrapper/tests/testrunner.py
- wrapper/virt_v2v_wrapper.py
RHBZ: https://bugzilla.redhat.com/show_bug.cgi?id=1814654
> OpenstackHost: Add suppport for two_phase conversion

- .travis.yml
Travis seems to fail on it from time to time for unknown reason.
> automation: run `./build.sh dist` verbosely

- docs/Virt-v2v-wrapper.md
- pylintrc
- wrapper/hosts.py
- wrapper/pre_copy.py
- wrapper/tests/test_pre_copy.py
- wrapper/virt_v2v_wrapper.py
This pull request adds two-phase migration for SSH transport method.
It also sets the default user to `root` as we connect to ESXi hosts, not vCenter.
RHBZ: https://bugzilla.redhat.com/show_bug.cgi?id=1817096
> Add two-phase migration for SSH transport method

- wrapper/pre_copy.py
Resolves: https://bugzilla.redhat.com/1820074
> pre_copy: Some extra logging

- kubevirt-vmware/pkg/controller/ovirtprovider/client.go
> ovirt: provide vnic id and network/vnic name

- wrapper/pre_copy.py
- wrapper/tests/test_pre_copy.py
Some requested fixups from #41.
> Minor fixups

- wrapper/log_parser.py
- wrapper/tests/test_output_parser.py
* Update regexp for nbdkit disk path
Co-authored-by: Martin Kletzander <mkletzan@redhat.com>
> Update regexp for nbdkit disk path

- kubevirt-vmware/pkg/controller/ovirtprovider/client.go
This PR helps to fix ability to edit/add vm description.
Bug-Url: https://bugzilla.redhat.com/1838683
> ovirt: fetch description

- build.sh
Prepare for nw kubevirt-vmware image release.
Signed-off-by: Jakub Dzon <jdzon@redhat.com>
> New kubevirt-vmware release

- kubevirt-vmware/pkg/controller/v2vvmware/client.go
When a host is not in the cluster `Parent` provide cluster with the same name as `host.Name()`. In this PR we detect such situation and remove duplication form `hostPath`.
Bug-Url: https://bugzilla.redhat.com/1841325
> Fix hostPath

- ansible/oVirt.v2v-conversion-host/tasks/install-transport-vddk.yml
> ansible: drop removed fact from check condition

- kubevirt-vmware/pkg/controller/gcovirtprovider/ovirtprovider_garbagecollector.go
We would like to add a label which would help us use default delete time for ovirt provider GC. By default we use 1hr which is based on vmware default value.
Bug-Url: https://bugzilla.redhat.com/1868045
> Add temporary label support

- kubevirt-vmware/pkg/controller/v2vvmware/actions.go
- kubevirt-vmware/pkg/controller/v2vvmware/client.go
@pkliczewski @mareklibra @nyoxi @nertpinx  please review
> Bug 1867980: do not fail kubevirt-vmware deployment when CR contains a space in URL

- wrapper/hosts.py
- wrapper/pre_copy.py
- wrapper/source_hosts.py
Fix linter errors:
* R1725: Consider using Python 3 style super() without arguments (super-with-arguments)
* W0707: Consider explicitly re-raising using the 'from' keyword (raise-missing-from)
> Fix linter errors R1725 and W0707

- kubevirt-vmware/pkg/controller/ovirtprovider/client.go
> Provide disk access mode

- kubevirt-vmware/pkg/controller/v2vvmware/client.go
- accept https and http scheme
> Bug 1884310: don't crash controller with invalid URLs

- vm-import-provider/go.mod
- vm-import-provider/vendor/modules.txt
> Update golang math/big

- vm-import-provider/pkg/controller/v2vvmware/actions.go
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1974297
Signed-off-by: Sam Lucidi <slucidi@redhat.com>
> Fix vmware status update
